# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hadoop_status.proto',
  package='flume_metrics',
  serialized_pb='\n\x13hadoop_status.proto\x12\rflume_metrics\"\x96\x01\n\x0cHadoopStatus\x12\x11\n\ttimestamp\x18\x01 \x02(\t\x12\x39\n\njob_status\x18\x02 \x03(\x0b\x32%.flume_metrics.HadoopStatus.JobStatus\x1a\x38\n\tJobStatus\x12\x0e\n\x06job_id\x18\x01 \x02(\t\x12\x0b\n\x03map\x18\x02 \x02(\x02\x12\x0e\n\x06reduce\x18\x03 \x02(\x02')




_HADOOPSTATUS_JOBSTATUS = descriptor.Descriptor(
  name='JobStatus',
  full_name='flume_metrics.HadoopStatus.JobStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='flume_metrics.HadoopStatus.JobStatus.job_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='map', full_name='flume_metrics.HadoopStatus.JobStatus.map', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reduce', full_name='flume_metrics.HadoopStatus.JobStatus.reduce', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=189,
)

_HADOOPSTATUS = descriptor.Descriptor(
  name='HadoopStatus',
  full_name='flume_metrics.HadoopStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='flume_metrics.HadoopStatus.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_status', full_name='flume_metrics.HadoopStatus.job_status', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HADOOPSTATUS_JOBSTATUS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=189,
)

_HADOOPSTATUS_JOBSTATUS.containing_type = _HADOOPSTATUS;
_HADOOPSTATUS.fields_by_name['job_status'].message_type = _HADOOPSTATUS_JOBSTATUS
DESCRIPTOR.message_types_by_name['HadoopStatus'] = _HADOOPSTATUS

class HadoopStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class JobStatus(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _HADOOPSTATUS_JOBSTATUS
    
    # @@protoc_insertion_point(class_scope:flume_metrics.HadoopStatus.JobStatus)
  DESCRIPTOR = _HADOOPSTATUS
  
  # @@protoc_insertion_point(class_scope:flume_metrics.HadoopStatus)

# @@protoc_insertion_point(module_scope)
