# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hadoop_status.proto',
  package='flume_metrics',
  serialized_pb='\n\x13hadoop_status.proto\x12\rflume_metrics\"\x91\x01\n\x0cHadoopStatus\x12\x11\n\ttimestamp\x18\x01 \x02(\t\x12\x35\n\x06status\x18\x02 \x03(\x0b\x32%.flume_metrics.HadoopStatus.JobStatus\x1a\x37\n\tJobStatus\x12\r\n\x05jobID\x18\x01 \x02(\t\x12\x0b\n\x03map\x18\x02 \x02(\x02\x12\x0e\n\x06reduce\x18\x03 \x02(\x02')




_HADOOPSTATUS_JOBSTATUS = descriptor.Descriptor(
  name='JobStatus',
  full_name='flume_metrics.HadoopStatus.JobStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='jobID', full_name='flume_metrics.HadoopStatus.JobStatus.jobID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='map', full_name='flume_metrics.HadoopStatus.JobStatus.map', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reduce', full_name='flume_metrics.HadoopStatus.JobStatus.reduce', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=184,
)

_HADOOPSTATUS = descriptor.Descriptor(
  name='HadoopStatus',
  full_name='flume_metrics.HadoopStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='flume_metrics.HadoopStatus.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='flume_metrics.HadoopStatus.status', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HADOOPSTATUS_JOBSTATUS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=184,
)

_HADOOPSTATUS_JOBSTATUS.containing_type = _HADOOPSTATUS;
_HADOOPSTATUS.fields_by_name['status'].message_type = _HADOOPSTATUS_JOBSTATUS
DESCRIPTOR.message_types_by_name['HadoopStatus'] = _HADOOPSTATUS

class HadoopStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class JobStatus(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _HADOOPSTATUS_JOBSTATUS
    
    # @@protoc_insertion_point(class_scope:flume_metrics.HadoopStatus.JobStatus)
  DESCRIPTOR = _HADOOPSTATUS
  
  # @@protoc_insertion_point(class_scope:flume_metrics.HadoopStatus)

# @@protoc_insertion_point(module_scope)
