# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hbase_status.proto',
  package='flume_metrics',
  serialized_pb='\n\x12hbase_status.proto\x12\rflume_metrics\"q\n\x0bHBaseStatus\x12\x11\n\ttimestamp\x18\x01 \x02(\t\x12\x14\n\x0cread_latency\x18\x02 \x02(\x02\x12\x15\n\rwrite_latency\x18\x03 \x02(\x02\x12\x14\n\x0csync_latency\x18\x04 \x02(\x02\x12\x0c\n\x04host\x18\x05 \x02(\t')




_HBASESTATUS = descriptor.Descriptor(
  name='HBaseStatus',
  full_name='flume_metrics.HBaseStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='flume_metrics.HBaseStatus.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='read_latency', full_name='flume_metrics.HBaseStatus.read_latency', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='write_latency', full_name='flume_metrics.HBaseStatus.write_latency', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sync_latency', full_name='flume_metrics.HBaseStatus.sync_latency', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='host', full_name='flume_metrics.HBaseStatus.host', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['HBaseStatus'] = _HBASESTATUS

class HBaseStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HBASESTATUS
  
  # @@protoc_insertion_point(class_scope:flume_metrics.HBaseStatus)

# @@protoc_insertion_point(module_scope)
